// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/cms/user/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Auth"
                ],
                "summary": "Generate JWT Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "lang",
                        "name": "Accept-Language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.BaseResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.RequestTimeoutResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        },
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/swagger.InternalServerErrorResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        },
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swagger.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "OK"
                },
                "data": {},
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "operasi berhasil dieksekusi."
                },
                "request_id": {
                    "type": "string",
                    "example": "24fa3770-628c-49de-aa17-3a338f73d99b"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2022-04-27 23:19:56"
                }
            }
        },
        "swagger.InternalServerErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "LBR-02-008"
                },
                "data": {},
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "terjadi kesalahan, silakan hubungi administrator."
                },
                "request_id": {
                    "type": "string",
                    "example": "24fa3770-628c-49de-aa17-3a338f73d99b"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2022-04-27 23:19:56"
                }
            }
        },
        "swagger.RequestTimeoutResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "LBR-02-009"
                },
                "data": {},
                "errors": {},
                "message": {
                    "type": "string",
                    "example": "permintaan telah melampaui batas waktu, harap request kembali."
                },
                "request_id": {
                    "type": "string",
                    "example": "24fa3770-628c-49de-aa17-3a338f73d99b"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2022-04-27 23:19:56"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Article App",
	Description:      "api \"API Article App V1\"",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
